### ISSUE TITLE
Fails to build with Python 3.9

### ISSUE THREAD

**Issue by fabaff** [jodal/pykka#96]
```bash
actor_class = <class 'tests.test_actor.actor_class.<locals>.ActorA'>
events = <tests.conftest.events.<locals>.Events object at 0x7f4372412820>

    @pytest.fixture
    def actor_ref(actor_class, events):
>       ref = actor_class.start(events)

tests/test_actor.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pykka/_actor.py:98: in start
    obj._start_actor_loop()
pykka/gevent.py:73: in _start_actor_loop
    gevent.Greenlet.spawn(self._actor_loop)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   AttributeError: type object 'method' has no attribute 'start'

src/gevent/greenlet.py:663: AttributeError
```

There are more failures.

Origin: https://bugzilla.redhat.com/show_bug.cgi?id=1834210

**Comment by jodal** [comment]
I see from https://github.com/python-greenlet/greenlet/pull/161 and https://github.com/python-greenlet/greenlet/blob/master/NEWS that Python 3.9 is only supported in the yet to be released greenlet 0.4.16 release.

What version of greenlet are you building with?

**Comment by fabaff** [comment]
0.4.14 (aka the [latest release](https://src.fedoraproject.org/rpms/python-greenlet) we have in Fedora)

**Comment by jodal** [comment]
I'd argue that this is a bug for greenlet then. It's the greenlet project that needs to publish a new release compatible with Python 3.9.

If there's anything that needs to be done in Pykka once greenlet runs on Python 3.9, please comment and I'll reopen the issue, or file a new issue.
